services:
  backend:
    build:
      context: ./backend
    container_name: nest_api
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/usr/src/app
    entrypoint: ["sh", "wait-for-mysql.sh"]
    depends_on:
      - db
    env_file:
      - ./backend/.env

  frontend:
    image: nginx:latest
    container_name: nginx_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - '3307:3306'
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: FolhaPonto
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: nestpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d:ro

volumes:
  mysql_data:

